name: kaggle_env
channels:
- conda-forge
dependencies:
- conda-forge::python=3.9
- conda-forge::notebook
- conda-forge::pandas=1.5
- conda-forge::seaborn=0.11
- conda-forge::scipy=1.9
- conda-forge::numpy=1.23
- conda-forge::plotnine=0.10
- conda-forge::scikit-learn
- conda-forge::umap-learn
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- pip=22.3
- pip:
  - black==22.3.0
  - flake8==3.8.4
  - pre_commit==2.9.3
  - kaggle